apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-pg
spec:
  selector:
    matchLabels:
      app: todo-app-pg
  template:
    metadata:
      labels:
        app: todo-app-pg
    spec:
      containers:
      - name: todo-app-pg
        image: oriolors/todoapp-pg
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: myconfigmap