apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvpostgresdb
spec:
  storageClassName: storageclass-postgres-db
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pvpostgresdb/