apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db-statfullset
spec:

  selector:
    matchLabels:
      app: postgres-db
  serviceName: postgres-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:10.4
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - name: pvclaim-postgres
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pvclaim-postgres
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: storageclass-postgres-db