apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db-statfullset
spec:
  selector:
    matchLabels:
      app: postgres-db
  serviceName: postgres-db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: posgres:10.4
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pvclaim-postgres
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pvclaim-postgres
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
