apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: ejercicio1
spec:
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: oriolors/lc-todo-monolith
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
          name: env-todo-app
