apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvtodoapp-pgs
spec:
  storageClassName: sc-todoapp-pg 
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pvtodoapp-pgs/